# Generated by Django 3.2.7 on 2021-10-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_user'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
